name: CI build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout DBeaver
        uses: actions/checkout@v2
        with:
          repository: dbeaver/dbeaver
          path: dbeaver

      - name: Build DBeaver
        working-directory: dbeaver/
        run: mvn clean install

      - name: Checkout OrbisRCP
        uses: actions/checkout@v2

      - name: Build OrbisRCP
        run: |
          git clone https://github.com/GroovyLanguageServer/groovy-language-server
          cd groovy-language-server
          ./gradlew build
          cd ..
          ls plugins/dependencies
          mkdir  plugins/dependencies/libs
          cp groovy-language-server/build/libs/groovy-language-server-all.jar ./plugins/dependencies/libs/groovy-language-server.jar
          mvn clean install

      - name: Unzip p2-1.0.0-SNAPSHOT.zip
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq ./p2/target/p2-1.0.0-SNAPSHOT.zip -d ./p2/target/p2-1.0.0-SNAPSHOT
          
          #- name: Push p2 build to another branch
          #uses: s0/git-publish-subdir-action@develop
          #env:
          #REPO: self
          #BRANCH: p2-repository 
          #FOLDER: ./p2/target/p2-1.0.0-SNAPSHOT 
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
